[package]
name = "ramp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
csv = "1.1.6"
ex = "0.1.3"
flate2 = "1.0.22"
futures-util = "0.3.19"
indicatif = "0.16.2"
log = "0.4.14"
ndarray = "0.15.4"
ndarray-npy = "0.8.1"
ordered-float = "2.8.0"
reqwest = { version = "0.11.8", features = ["stream"] }
serde = { version = "1.0.132", features = ["derive"] }
simplelog = "0.11.1"
tar = "0.4.38"
tokio = { version = "1.15.0", features = ["full"] }

# See https://doc.rust-lang.org/cargo/reference/profiles.html#overrides. This
# compiles all external dependencies in release mode, yielding great runtime
# speed, but only paying the cost of slow compilation once (since we don't
# update dependencies often).
[profile.dev.package."*"]
opt-level = 3
