[package]
name = "ramp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
cap = "0.1.0"
clap = "2.34.0"
csv = "1.1.6"
enum-map = "1.1.1"
flate2 = "1.0.22"
fs-err = "2.6.0"
futures-util = "0.3.19"
geo = "0.18.0"
geojson = { version = "0.22.2", features = ["geo-types"] }
indicatif = { git = "https://github.com/dabreegster/indicatif", branch = "human_count" }
log = "0.4.14"
ndarray = "0.15.4"
ndarray-npy = "0.8.1"
ordered-float = "2.8.0"
reqwest = { version = "0.11.8", features = ["stream"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
shapefile = { version = "0.3.0", features = ["geo-types"] }
simplelog = "0.11.1"
structopt = "0.3.25"
tar = "0.4.38"
tokio = { version = "1.15.0", features = ["full"] }

# See https://doc.rust-lang.org/cargo/reference/profiles.html#overrides. This
# compiles all external dependencies in release mode, yielding great runtime
# speed, but only paying the cost of slow compilation once (since we don't
# update dependencies often).
[profile.dev.package."*"]
opt-level = 3
