[package]
name = "ramp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
csv = "1.1.6"
env_logger = "0.9.0"
futures-util = "0.3.19"
indicatif = "0.16.2"
log = "0.4.14"
maplit = "1.0.2"
ndarray = "0.15.4"
ndarray-npy = "0.8.1"
ordered-float = "2.8.0"
reqwest = { version = "0.11.8", features = ["stream"] }
serde = { version = "1.0.132", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }
